kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.name}}
  labels:
    app: {{ .Values.name}}
    app.kubernetes.io/component: {{ .Values.name}}
    app.kubernetes.io/instance: {{ .Values.name}}
    app.kubernetes.io/name: {{ .Values.name}}
    app.kubernetes.io/part-of: {{ .Values.name}}
    app.openshift.io/runtime-namespace: {{ .Values.name}}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
        deployment: {{ .Values.name}}
    spec:
      containers:
        - name: {{ .Values.name}}
          image: >- 
              quay.io/dgarciap/spring-petclinic:{{.Values.version}}
          ports:
            - containerPort: {{ .Values.port1}} 
              protocol: {{ .Values.portsprotocol}}
            - containerPort: {{ .Values.port2}}
              protocol: {{ .Values.portsprotocol}}
            - containerPort: {{ .Values.port3}}
              protocol: {{ .Values.portsprotocol}}
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
