kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.name}}
  labels:
    app: {{ .Values.name}}
    app.kubernetes.io/component: {{ .Values.name}}
    app.kubernetes.io/instance: {{ .Values.name}}
    app.kubernetes.io/name: {{ .Values.name}}
    app.kubernetes.io/part-of: {{ .Values.name}}
    app.openshift.io/runtime-version: 0.1.0
spec:
  host: {{ .Values.name}}-{{ .Values.name}}.apps.ocp.sandbox{{ .Values.guid}}.opentlc.com
  to:
    kind: Service
    name: {{ .Values.name}}
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None